#!/bin/bash

set -e
set -o pipefail

if [ "$#" != 2 ]; then
    echo "Invalid number of arguments: $#."
    echo "Usage: $0 <input file> <out dir>"
    exit 1
fi

. scripts/run_in_docker.sh

# delete any snippet generated by a previous run
rm -f "$2/$(basename -s .tex "$1").{snippets,pygmented}"

# we this env var we communicate with our custom 'pygmenter_xelatex'
# script which file look for pygment
export PYGMENTE_TARGET="$2/$(basename -s .tex "$1")"


#run_in_docker \
latexmk \
    -Werror \
    -xelatex \
    -pdfxe \
    -pdfxelatex="./scripts/pygmenter_xelatex.sh %O %S" \
    -outdir="$2" \
    "$1" > "$2/$(basename -s .tex "$1").console_log" 2>&1

